
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  flyway:
     enabled: false

server:
  port: 8080

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

springdoc:
  api-docs:
     path: /api-docs
  swagger-ui:
     path: /swagger-ui/index.html