spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zayka
    username: zayka
    password: zayka
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
server:
  port: 8080
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
